<a href="https://colab.research.google.com/github/jiin124/Introduction-to-NLP-using-deep-learning/blob/main/PyTorch/02_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. 넘파이로 벡터 만들기(벡터와 행렬 만들기)

In [1]:
import numpy as np

## 1) 1D with numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t:',t.ndim)#몇 차원인지 출력
print('Shape of t:',t.shape)#크기 출력(1,7)

Rank of t: 1
Shape of t: (7,)


In [4]:
t[4:-1]

array([4., 5.])

## 2) 2D with Numpy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


# 3. 파이토치 텐서 선언하기


In [7]:
import torch

## 1) 1D with PyTorch

In [8]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(t.dim())#차원
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [10]:
#슬링싱
print(t[0],t[1],t[-1])#인덱스 접근
print(t[2:5],t[4:-1])#슬라이싱
print(t[:2],t[3:])#슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2) 2D with PyTorch

In [11]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [13]:
#슬라이싱
print(t[:,1])#첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:,1].size())#위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [14]:
print(t[:,:-1])# 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## 3) 브로드캐스팅

행렬의 덧셈과 뺄셈에서는 두행렬 a,b의 크기가 같아야 한다. 두 행렬이 곱셈을 할ㄸ는 a의 마지막 차원과 b의 첫번재 차원이 일치해야 한다. 

불가피하게 크기가 다른 행렬 또는 텐서에 대해서 사칙 연산을 수행할 필요가 있는 경우가 생긴다. 이를 ㅜ이해 파이토치에서는 자동으로 크기를 맞추ㅕ 연산을 수행하게 만드는 브로드캐스팅이라는 기능을 제공한다. 

In [15]:
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [16]:
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3])# [3] -> [3, 3]

print(m1+m2)

tensor([[4., 5.]])


수학적으로는 원래 연산이 안되는데 파이토치에서는 브로드캐스팅을 통해 이를 연산한다. 

In [17]:
m1=torch.FloatTensor([[1,2,]])
m2=torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])




```
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
```



## 4) 자주 사용되는 기능들

### 1) 행렬 곱셈과 곱셈의 차이

행렬로 곱셈을 하는 방법은 크게 두가지가 있다. 바로 행렬곱셈과 원소 별 곱셈이다. 

In [18]:
#행렬곱셈 matmul()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [19]:
#원소별곱셈 mul()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


m1 행렬의 크기는 2,2 이었다. m2 행렬의 크기는 (2,1) 였다. 이때 element-wise 곱셈을 수행하면 두 행렬의 크기는 브로드캐스팅이 된 후에 곰셈이 수행된다. 



```
# 브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.
[1]
[2]
==> [[1, 1],
     [2, 2]]
```



### 2) 평균(Mean)

In [20]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [22]:
#2차원 행렬
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(t.mean())

tensor(2.5000)


4개의 원소의 평균인 2.5가 나왔습니다. 이번에는 dim. 즉, 차원(dimension)을 인자로 주는 경우를 보겠습니다.

In [24]:
print(t.mean(dim=0))

tensor([2., 3.])


dim=0이라는 것은 첫번째 차원을 의미한다. 행렬에서 첫번째 차원은 행을 의미한다. 그리고 인자로 dim을 준다면 해당 차원을 제거한다는 의미가 된다. 다시 말해 열만 남기겠다는 의미가 된다. 기존 행렬의 크기는 (2,2)였지만 이를 수행하면 열의 차원만 보존되면서 (1,2)가 된다. 이는 (2,)와 같으며 벡터이다. 열의 차원을 보존하면서 평균을 구하면 아래와 같이 연산한다. 



```
# 실제 연산 과정
t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.

[[1., 2.],
 [3., 4.]]

1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
결과 ==> [2., 3.]
```



In [25]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


 이번에는 dim=-1를 주는 경우를 보겠습니다.

In [26]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


### 3) 덧셈(Sum)

In [27]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### 4) 최대와 아그맥스(ArgMax)

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.max()) # Returns one value: max

tensor(4.)


In [31]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
